### ISSUE TITLE
AppSpector Flutter Plugin makes the iOS App Crash if there is no Internet Connection

### ISSUE THREAD

**Issue by krutarth-h-dave** [appspector/flutter-plugin#40] opened 2021-03-11 13:11 UTC
AppSpector Integration with iOS Crashes when User opens the App in Offline Mode:

```Pubspec.yaml
appspector: ^0.6.0

appspector:
    dependency: "direct main"
    description:
      name: appspector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.0"
```

Crash Logs:
```-[NSNull data]: unrecognized selector sent to instance 0x1c99c61e0
(
	0   CoreFoundation                      0x0000000187c0c314 AF42303F-57B6-3C11-8F18-8E80ABF7D886 + 1254164
	1   libobjc.A.dylib                     0x0000000187920c1c objc_exception_throw + 60
	2   CoreFoundation                      0x0000000187b0aa90 AF42303F-57B6-3C11-8F18-8E80ABF7D886 + 199312
	3   CoreFoundation                      0x0000000187c10a60 AF42303F-57B6-3C11-8F18-8E80ABF7D886 + 1272416
	4   CoreFoundation                      0x0000000187c12d60 _CF_forwarding_prep_0 + 96
	5   appspector                          0x0000000104422284 -[ASPluginEventsHandler handleResponseCall:result:] + 228
	6   appspector                          0x0000000104421d80 -[ASPluginEventsHandler handleMethodCall:result:] + 560
	7   Flutter                             0x0000000104fff468 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 116
	8   Flutter                             0x00000001047e13b0 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 504
	9   Flutter                             0x0000000104acfff0 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_34NS_9allocatorIS8_EEFvvEEclEv + 108
	10  Flutter                             0x0000000104a6f798 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 1472
	11  Flutter                             0x0000000104a71db8 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 32
	12  CoreFoundation                      0x0000000187b88190 AF42303F-57B6-3C11-8F18-8E80ABF7D886 + 713104
	13  CoreFoundation                      0x0000000187b87ea8 AF42303F-57B6-3C11-8F18-8E80ABF7D886 + 712360
	14  CoreFoundation                      0x0000000187b8751c AF42303F-57B6-3C11-8F18-8E80ABF7D886 + 709916
	15  CoreFoundation                      0x0000000187b82274 AF42303F-57B6-3C11-8F18-8E80ABF7D886 + 688756
	16  CoreFoundation                      0x0000000187b818f4 CFRunLoopRunSpecific + 480
	17  GraphicsServices                    0x0000000191f98604 GSEventRunModal + 164
	18  UIKitCore                           0x000000018bd55358 UIApplicationMain + 1944
	19  Runner                              0x0000000102d82020 main + 88
	20  libdyld.dylib                       0x00000001879fd2dc E5E56A85-E4D6-332E-9F32-FED4B986AFE0 + 4828
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001879f2df0 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1879f2df0 <+8>:  b.lo   0x1879f2e0c               ; <+36>
    0x1879f2df4 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1879f2df8 <+16>: mov    x29, sp
    0x1879f2dfc <+20>: bl     0x1879d10e8               ; cerror_nocancel
Target 0: (Runner) stopped.```

**Comment by Dimdron** [comment] 2021-03-11 13:33
Hi, thanks for report! Could you try to update your pods to use the latest native SDK version?

**Comment by Dimdron** [comment] 2021-03-11 13:33
And which device are you using?

**Comment by krutarth-h-dave** [comment] 2021-03-11 13:38
@Dimdron Can you tell me what exactly it means by updating the pods to use the latest native SDK version? The Pods are updated if I am not mistaken. However I can be wrong.
About the device, It is not device specific but in general crashes for any devices operating on iOS.
iPhone 7, iPhone XR, iPhone 12 are one of them where it crashed.

**Comment by Dimdron** [comment] 2021-03-11 13:45
You need to run the command `pod update AppSpectorSDK` at the `yourProject/ios` directory from terminal

**Comment by krutarth-h-dave** [comment] 2021-03-11 13:47
Sure. To update, I was already on AppSpectorSDK version 1.4.0 which is latest.

**Comment by krutarth-h-dave** [comment] 2021-03-12 09:34
@Dimdron Hi, any update on this?

**Comment by Dimdron** [comment] 2021-03-12 09:37
I have redirected the issue to the iOS team. @deszip have you found something?

**Comment by krutarth-h-dave** [comment] 2021-03-12 09:39
Thanks @Dimdron , Let me know if anyway I can help.

**Comment by reface-ios-cicd** [comment] 2021-03-12 09:48
Hi @krutarth-h-dave , thanks for reporting, I'll take a look today.
Regarding stacktrace you provided, looks like an exception, can you pls check if you have exception description?
Should be a couple of lines before the chunk you provided.

**Comment by deszip** [comment] 2021-03-12 09:50
Hi @krutarth-h-dave , thanks for reporting, I'll take a look today.
Can you please check if you have an exception description in logs? Should be before the chunk you provided above.

**Comment by krutarth-h-dave** [comment] 2021-03-12 13:49
@deszip 
```
-[NSNull data]: unrecognized selector sent to instance 0x1d5d6dee0
(
	0   CoreFoundation                      0x00000001847099ec F3021642-E3C0-33F8-9911-DD303A6056D0 + 1157612
	1   libobjc.A.dylib                     0x0000000198a8fb54 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000184619bbc F3021642-E3C0-33F8-9911-DD303A6056D0 + 175036
	3   CoreFoundation                      0x000000018470c01c F3021642-E3C0-33F8-9911-DD303A6056D0 + 1167388
	4   CoreFoundation                      0x000000018470df8c _CF_forwarding_prep_0 + 92
	5   appspector                          0x00000001019ba284 -[ASPluginEventsHandler handleResponseCall:result:] + 228
	6   appspector                          0x00000001019b9d80 -[ASPluginEventsHandler handleMethodCall:result:] + 560
	7   Flutter                             0x0000000102597468 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 116
	8   Flutter                             0x0000000101d793b0 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 504
	9   Flutter                             0x0000000102067ff0 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_34NS_9allocatorIS8_EEFvvEEclEv + 108
	10  Flutter                             0x0000000102007798 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 1472
	11  Flutter                             0x0000000102009db8 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 32
	12  CoreFoundation                      0x000000018468a3e0 F3021642-E3C0-33F8-9911-DD303A6056D0 + 635872
	13  CoreFoundation                      0x0000000184689fe4 F3021642-E3C0-33F8-9911-DD303A6056D0 + 634852
	14  CoreFoundation                      0x00000001846894c4 F3021642-E3C0-33F8-9911-DD303A6056D0 + 632004
	15  CoreFoundation                      0x0000000184683850 F3021642-E3C0-33F8-9911-DD303A6056D0 + 608336
	16  CoreFoundation                      0x0000000184682ba0 CFRunLoopRunSpecific + 572
	17  GraphicsServices                    0x000000019b3eb598 GSEventRunModal + 160
	18  UIKitCore                           0x0000000186f742f4 CC6E5AC7-8248-35F6-8B42-2E25C93DCF0A + 11723508
	19  UIKitCore                           0x0000000186f79874 UIApplicationMain + 164
	20  Runner                              0x00000001002e6020 main + 88
	21  libdyld.dylib                       0x0000000184361568 0B475C78-3C12-3121-B7F8-2B95B83DAF44 + 5480
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001b064884c libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1b064884c <+8>:  b.lo   0x1b0648868               ; <+36>
    0x1b0648850 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1b0648854 <+16>: mov    x29, sp
    0x1b0648858 <+20>: bl     0x1b0625f5c               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.

```

**Comment by deszip** [comment] 2021-03-12 14:07
Great, thanks, I'll post an update here when we'll have a fix

**Comment by krutarth-h-dave** [comment] 2021-03-13 05:56
@deszip Sure, waiting for the same.

**Comment by deszip** [comment] 2021-03-14 10:49
@krutarth-h-dave I wasn't able to reproduce the issue itself but have a fix for a potential cause. It's still in review, you can try it using the PR branch or wait until it will be merged in a day or two.

I'm not sure if it's possible to target in you project to specific branch of the plugin repo, maybe smth like this will work:
```
appspector:
    git:
      url: git@github.com:appspector/flutter-plugin.git
      ref: fix/null-argument-handling
```

**Comment by krutarth-h-dave** [comment] 2021-03-14 12:07
Sure @deszip , Let me try this. I will get back to you.

**Comment by krutarth-h-dave** [comment] 2021-03-14 16:37
@deszip I did try the v6.0.1 version by ref and it is working fine. Great stuff. Waiting for this change to get merged and released. Thanks @deszip @Dimdron !

**Closed** 2021-03-17 18:28 UTC
